apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dns-lexicon-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gradecam/cert-manager-dns-lexicon-webhook
    targetRevision: main
    path: deploy/cert-manager-dns-lexicon-webhook
    helm:
      releaseName: dns-lexicon-webhook
      values: |
        groupName: acme.uxn.nl
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
