namespace: ingress-nginx

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml

replicas:
  - name: ingress-nginx-controller
    count: 1

patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        loadBalancerIP: 192.168.69.101
